// Available models on OpenRouter - curated list of free/low-cost models
// Updated: 2026-09-04 - Models verified on OpenRouter
import { ModelInfo } from "./types";

export const AVAILABLE_MODELS: ModelInfo[] = [
  {
    id: "nvidia/nemotron-3-ultra-550b-a55b:free",
    name: "Nemotron 3 Ultra 550B",
    provider: "NVIDIA",
    contextLength: 1048576,
    pricing: "Free (rate limited)",
    free: true,
    description: "550B total params (55B active) MoE, Transformer-Mamba hybrid, agentic workflows & reasoning",
  },
  {
    id: "apodex/apodex-1.1-mini:free",
    name: "Apodex 1.1 Mini",
    provider: "Apodex",
    contextLength: 131072,
    pricing: "Free (rate limited)",
    free: true,
    description: "Lightweight efficient model for fast responses",
  },
  {
    id: "nvidia/nemotron-3.5-lightning:free",
    name: "Nemotron 3.5 Lightning",
    provider: "NVIDIA",
    contextLength: 262144,
    pricing: "Free (rate limited)",
    free: true,
    description: "Fast inference Nemotron variant optimized for speed",
  },
  {
    id: "nvidia/nemotron-3-super-120b-a12b:free",
    name: "Nemotron 3 Super 120B",
    provider: "NVIDIA",
    contextLength: 262144,
    pricing: "Free (rate limited)",
    free: true,
    description: "120B total params (12B active) MoE, balanced performance and efficiency",
  },
  {
    id: "thinkingmachines/inkling:free",
    name: "Inkling",
    provider: "ThinkingMachines",
    contextLength: 131072,
    pricing: "Free (rate limited)",
    free: true,
    description: "Reasoning model from ThinkingMachines",
  },
  {
    id: "qwen/qwen3.8-27b:free",
    name: "Qwen 3.8 27B",
    provider: "Alibaba",
    contextLength: 131072,
    pricing: "Free (rate limited)",
    free: true,
    description: "Alibaba's Qwen model, strong coding and math capabilities",
  },
  {
    id: "inclusionai/ling-3.1-flash",
    name: "Ling 3.1 Flash",
    provider: "Inclusion AI",
    contextLength: 131072,
    pricing: "Free (rate limited)",
    free: true,
    description: "Inclusion AI's fast model variant",
  },
  {
    id: "thinkingmachines/inkling-small:free",
    name: "Inkling Small",
    provider: "ThinkingMachines",
    contextLength: 131072,
    pricing: "Free (rate limited)",
    free: true,
    description: "Smaller variant of Inkling, faster and more efficient",
  },
  {
    id: "cohere/north-mini-code:free",
    name: "North Mini Code",
    provider: "Cohere",
    contextLength: 262144,
    pricing: "Free (rate limited)",
    free: true,
    description: "30B MoE (3B active), Apache 2.0 licensed, code-focused model",
  },
];