// Available models on OpenRouter - curated list of free/low-cost models
import { ModelInfo } from "./types";

export const AVAILABLE_MODELS: ModelInfo[] = [
  {
    id: "deepseek/deepseek-r1:free",
    name: "DeepSeek R1",
    provider: "DeepSeek",
    contextLength: 16384,
    pricing: "Free (rate limited)",
    free: true,
    description: "Frontier reasoning model with chain-of-thought",
  },
  {
    id: "meta-llama/llama-4-maverick:free",
    name: "Llama 4 Maverick",
    provider: "Meta",
    contextLength: 131072,
    pricing: "Free (rate limited)",
    free: true,
    description: "Meta's latest hybrid MoE model, strong reasoning",
  },
  {
    id: "meta-llama/llama-4-scout:free",
    name: "Llama 4 Scout",
    provider: "Meta",
    contextLength: 131072,
    pricing: "Free (rate limited)",
    free: true,
    description: "Fast and efficient hybrid MoE model",
  },
  {
    id: "qwen/qwen3-235b-a2b:free",
    name: "Qwen3 235B A2B",
    provider: "Alibaba",
    contextLength: 131072,
    pricing: "Free (rate limited)",
    free: true,
    description: "Alibaba's hybrid MoE model, excellent at coding and math",
  },
  {
    id: "qwen/qwen3-30b-a3b:free",
    name: "Qwen3 30B A3B",
    provider: "Alibaba",
    contextLength: 131072,
    pricing: "Free (rate limited)",
    free: true,
    description: "Efficient Qwen3 model with strong performance",
  },
  {
    id: "mistralai/mistral-small-3.1:free",
    name: "Mistral Small 3.1",
    provider: "Mistral AI",
    contextLength: 32768,
    pricing: "Free (rate limited)",
    free: true,
    description: "Fast, cost-effective model for general tasks",
  },
  {
    id: "mistralai/mistral-7b-instruct:free",
    name: "Mistral 7B Instruct",
    provider: "Mistral AI",
    contextLength: 8192,
    pricing: "Free (rate limited)",
    free: true,
    description: "Lightweight Mistral model for quick responses",
  },
  {
    id: "microsoft/phi-4-mini-instruct:free",
    name: "Phi 4 Mini",
    provider: "Microsoft",
    contextLength: 131072,
    pricing: "Free (rate limited)",
    free: true,
    description: "Microsoft's efficient small model, surprisingly capable",
  },
  {
    id: "microsoft/phi-4:free",
    name: "Phi 4",
    provider: "Microsoft",
    contextLength: 131072,
    pricing: "Free (rate limited)",
    free: true,
    description: "Mid-size model with strong reasoning and knowledge",
  },
  {
    id: "google/gemini-2.5-flash-lite:free",
    name: "Gemini 2.5 Flash Lite",
    provider: "Google",
    contextLength: 1048576,
    pricing: "Free (rate limited)",
    free: true,
    description: "Ultra-fast model with massive context window",
  },
  {
    id: "google/gemma-3-12b-it:free",
    name: "Gemma 3 12B IT",
    provider: "Google",
    contextLength: 131072,
    pricing: "Free (rate limited)",
    free: true,
    description: "Google's open model, good general-purpose assistant",
  },
  {
    id: "google/gemma-3-27b-it:free",
    name: "Gemma 3 27B IT",
    provider: "Google",
    contextLength: 131072,
    pricing: "Free (rate limited)",
    free: true,
    description: "Stronger Gemma variant with better reasoning",
  },
  {
    id: "nousresearch/nous-hermes-3-8b:free",
    name: "Nous Hermes 3 8B",
    provider: "Nous Research",
    contextLength: 131072,
    pricing: "Free (rate limited)",
    free: true,
    description: "Capable general-purpose model with strong instruction following",
  },
  {
    id: "minimax/minimax-m2.1:free",
    name: "MiniMax M2.1",
    provider: "MiniMax",
    contextLength: 131072,
    pricing: "Free (rate limited)",
    free: true,
    description: "Frontier reasoning model with strong Chinese support",
  },
  {
    id: "anthropic/claude-sonnet-4-5:free",
    name: "Claude Sonnet 4.5",
    provider: "Anthropic",
    contextLength: 200000,
    pricing: "Free tier available",
    free: true,
    description: "Anthropic's flagship model, excellent at creative tasks",
  },
  {
    id: "anthropic/claude-haiku-4:free",
    name: "Claude Haiku 4",
    provider: "Anthropic",
    contextLength: 200000,
    pricing: "Free tier available",
    free: true,
    description: "Fastest Claude model, great for quick responses",
  },
];